### ISSUE TITLE
Updates to the POST validation based on the updated mapping file

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#178]
Add current missing fields in [recent schema update](https://github.com/18F/fs-permit-api-schemas/blob/master/special-use/special-use-POST-suds-mapping-post.json).

**Comment by cameronwolf** [comment]
Still need to implement validation for these:
"individualIsCitizen" : { "type" : "boolean", "note" : "Required if contactType is individual."},
"smallBusiness" : { "type" : "boolean", "note" : "Required if contactType is not individual."},
