### ISSUE TITLE
Move AWS config into config AWS credential file

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#202]
from [Sprint 3 PR review](https://github.com/18F/fs-middlelayer-api/pull/8#pullrequestreview-29804855):

> Let's move the AWS config to its own file in the config, so that in the future it will be a bit more swappable.

**Comment by brianfunk** [comment]
Should already work with AWS credential file.  Need to test and confirm.

**Comment by brianfunk** [comment]
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html
