### ISSUE TITLE
Handle 404 from Basic API

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#297]
If there is a error in Basic API or Basic API not available, the response code is 404 in the header with a message in the body  contains the 404 message. The middle-layer API needs to handle this response. 

(Comments below apply to #314 .)

**Comment by lauraGgit** [comment]
Actually! turns out the endpoint for a person should be
`/contact/lastname/{lastname}`
and for and org should be 
`/contact/orgcode/{orgcode}`

or if available
`/contact/{contcn}`

**Comment by lauraGgit** [comment]
/contact/person is only for the post
