### ISSUE TITLE
Restrict applications access

### ISSUE THREAD

**Issue by brianfunk** [nci-ats/fs-middlelayer-api#3]
## User Story 
As a system administrator, I would like to restrict which applications have the access to reading and writing to the SUDS database restricted.

## Acceptance Criteria

- The ePermit API restricts basic API access to single-level authorization.
- Authentication uses JSON web tokens for GET, POST, and PUT requests.
- The ePermit API returns a 403 status code if the user is unauthorized.
- The ePermit API returns a 401 status code if the user is not authenticated or authentication failed.
- The ePermit API returns a 200 status code if the user is authorized and authenticated.

**Comment by lauraGgit** [comment]
I'm just wondering if we want to add to the acceptance criteria, that if the tokens are valid that a 200 response it issued?
