### ISSUE TITLE
ContId required in contact/person and  org post route

### ISSUE THREAD

**Issue by lauraGgit** [nci-ats/fs-middlelayer-api#301]
I'm not entirely sure how to add this to the [validation schema](https://github.com/nci-ats/fs-middlelayer-api/blob/4c2bfd38e8e9ec04c22e3bd61acdaa5095ba1285/src/controllers/validation.json) myself but for both ["applicantInfoNoncommercial"](https://github.com/nci-ats/fs-middlelayer-api/blob/dev/src/api.json#L457) and ["applicantInfoTempOutfitter"](https://github.com/nci-ats/fs-middlelayer-api/blob/dev/src/api.json#L494) to add the "contId" that reflects the person's last name if they are an individual or org name for organizations. And weirdly, it has to be all caps. /shrug.

**Comment by lpendem** [comment]
@lauraGgit Can you add a sample POST request to Basic API and it's expected response?

**Comment by lauraGgit** [comment]
Notes on this:

1.      What is the algorithm used to generate contID in a post request, should we just be augmenting "EPERMIT PERSON X"?
For person, contId should be person's name; for organization, contId normally is as same as orgCode, and contName is the organization name. My testing data is not real data. I planned to remove them after testing, that is why I gave the data like EPERMIT…..
for example,
person (contId): TAYLOR, GERD,
organization (contId, contName, orgCode):
HUPFER,B           THE EUNICE E. HUPFER LIVING TRUST          HUPFER,B   
MCC,MISSOULA           MONTANA CONSERVATION CORPS, INC.      MCC,MISSOULA

**Comment by lauraGgit** [comment]
Person: LASTNAME, FIRSTNAME
Organization: UPPERORGCODE

**Comment by lauraGgit** [comment]
person- 
{ contID: "",
"firstName: "",
"lastName: ""
}

**Comment by lauraGgit** [comment]
@lpendem & @cameronwolf fyi its `contId` not `contID`
I also posted the response in #318

**Comment by lauraGgit** [comment]
also fyi for post should be `contact/person` with no trailing slash - https://github.com/nci-ats/fs-middlelayer-api/blob/dev/src/controllers/basic.js#L179
