### ISSUE TITLE
Change search contact Basic API call

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#314]
from issue #297:
> ...the endpoint for a person should be
> /contact/lastname/{lastname} currently on https://github.com/nci-ats/fs-middlelayer-api/blob/dev/src/controllers/basic.js#L264
> and for and org should be
> /contact/orgcode/{orgcode}
> 
> or if available
> /contact/{contcn}
> 
> The trailing / at the end of the request is also not part of the uri.
> 
> /contact/person is only for the post

**Comment by cameronwolf** [comment]
For POST:
/contact/person
/contact/orgcode

For GET:
/contact/orgcode/{orgCode}
/contact/lastname/l{lastName}
