### ISSUE TITLE
Handle contact found

### ISSUE THREAD

**Issue by lauraGgit** [nci-ats/fs-middlelayer-api#335]
the contact/lastname response returns an array with the following response objects inside:
```
[ { contCn: '777779010848',
   contId: 'TESTLAST39,TESTFIRST39',
   contName: null,
   contactType: 'PERSON',
   firstName: 'Testfirst39',
   lastName: 'Testlast39',
   orgCode: null,
   orgType: null,
   personPrefix: null,
   securityId: ' 0102' } ]
```

Seems like we need to update the contact check to handle three scenarios if a contact is found:
- [ ] One contact Found
     ```
     if(res.length == 1  && res[0].contCn){
          return Promise.resolve(res[0].conCn)
     }
    ```
- [ ] More found but only 1 matching ContId:
     -- iterate through each contId and see if that matches the one that we would use, if only one matching contId then return that contId
- [ ] More than 1 matching ContId:
   if multiple contIds end up matching then gather the addresses and send them back to the frontend as a multiple found

**Comment by lpendem** [comment]
@lauraGgit An additional condition also implemented, If none of the contId matches from results with the input contId then it will create new contact POST.
