### ISSUE TITLE
Post an organization to /contact/organization

### ISSUE THREAD

**Issue by lauraGgit** [nci-ats/fs-middlelayer-api#352]
Line 285 src/controllers/basic.js  change the route to /contact/organization

/contact/orgcode/{orgcode} is the `GET` route.

**Comment by lauraGgit** [comment]
And need to post convert the post for `contName` to `orgCode` on src/controllers/validation.js L#36

**Comment by cameronwolf** [comment]
@lauraGgit Line 285 does not determine which URL the request is sent to, that is just the index in the object containing all of the POST objects.  If you'd like I can still update it to prevent confusion in the future.
