### ISSUE TITLE
Implement field-specific validation

### ISSUE THREAD

**Issue by janwilli** [nci-ats/fs-middlelayer-api#91]
(e.g., zip code, phone number)

**Comment by colinpmacarthur** [comment]
Hi @cameronwolf and @janwilli:

Just to make sure we're all on the same page, I think we expect validation on the following fields:

* State (two letters)
* ZIP (5 or 9 numbers)
* Phone number (think you already covered this)
* Forest, region and district should each be two digit integers
* startTime and endTime should be dateTime objects

**Comment by janwilli** [comment]
Yes; sounds good, @colinpmacarthur. Thanks.
